config/routes.rb
Rails.application.routes.draw do

  get 'areas/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'history' => 'static_pages#history'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'building' => 'static_pages#building'
  get 'news' => 'newsposts#news_page'
  get 'signup' => '#' #'users#new'
  get 'testpage' => 'static_pages#testpage'
  get 'delete_inactive_users' => 'users#delete_inactive_users'
  get 'messages' => 'messages#messages_board'
  get 'new_area' => 'areas#new'
  get 'worldmap' => 'areas#index'
  get 'showallareas' => 'areas#showall'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :newsposts, only: [:create, :edit, :update, :destroy]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :areas

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  # def history
  # end

  def help
  end

  def contact
  end
  
  def about
  end
  
  def building
  end
  
  def testpage
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="about_contact">
  <h3 class="align_center">
    About This Website<br><br>
    <small>
      <font color="d1d1d1">
        This website was written by your truely Seita (
        <%= link_to "LinkedIn", 
            "https://www.linkedin.com/in/au-lee-216779120", 
            :target => "blank" %>
        ).  It was written while I
        was learning Ruby on Rails.  Since the old StrangeMUD website can use 
        an update, I decided to use this opportunity to see what I can do with 
        the stuffs I learned.<br>
        <br>
        <a target="blank" href='https://bitbucket.org/Evilmuffin/strange/src'>
          Source
        </a>
      </font>
    </small>
  </h3>
</div>
    

app/views/static_pages/building.html.erb
<% provide(:title, "Building") %>
<body>
  <div class="center jumbotron">
    <font color="d1d1d1">
      <h1>Building</h1>
    </font>
    <h3>
      <%= image_tag("tools1.png") %>
    </h3>
    <p>
      <small>
        So you want to build an area?  Sure! Go knock yourself out!<br>
        <br>
        No, I'm not kidding.  Anyone may build an area for StrangeMUD.  Prior 
        building experience with StrangeMUD, or any mud, is not necessary, nor 
        is any programming skill required.  It is, however, helpful if you have
        some familiarity with StrangeMUD and its existing areas.<br>
        <br>
        Areas on StrangeMUD (unlike some other MUDs) are not restricted by 
        theme. You may choose to write a medieval-themed area, or you may 
        choose to model it after a modern city. You may base it on a favorite 
        book, movie, or legend, or you may simply make it up as you go along. 
        Any reasonably creative content is eligible for implementation. 
        Of course, any discriminatory or harassing content will not be 
        accepted. Please use common sense, and if you are in doubt, ask an 
        immortal.<br>
        <br>
        The only requirement for area creation is a good idea. Helpful tools 
        include a computer with a text editor (such as DOS edit or 
        Notepad/WordPad for Windows).  You may also use a text editor in an 
        ISP shell account, such as Pico for Unix/Linux.<br>
        <br>
        While it is not necessary to notify us of your intent, doing so will 
        let you know if an area of your theme has already been implemented or 
        is under construction.  The best contact would be Seita, head of 
        building.<br>
        <br>
        Many of our immortals have building experience, and will gladly answer 
        any questions they can. In addition, the builder's documents 
        (CircleMUD builder's docs revised to apply specifically to StrangeMUD) 
        are freely available in this section.<br>
        </small>
    </p>
    <ul id="download_links">
      <li>
        <%= link_to "Building DOCS", '/files/blddoc.txt', 
            :target => '_blank' %>
      </li>
      <li>
        <%= link_to "StrangeMUD Reference", '/files/StrangeMUD_refernce.xls', 
            :target => '_blank' %>
      </li>
      <li>
        <%= link_to "Room Entry and Exit", '/files/Wld-EntryExit.txt', 
            :target => '_blank' %>
      </li>
      <li>
        <%= link_to "MPSET", '/files/MPSET.REF', 
            :target => '_blank' %>
      </li>
      <li>
        <%= link_to "Social Guide", '/files/socguide.txt', 
            :target => '_blank' %>
      </li>
    </ul>
  </div>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="about_contact">
  <h3 class="align_center">
    Contact<br><br>
      <small>
        <font color="d1d1d1">
        If you have any question about this website or the game, feel free 
        to MUDmail Seita.
        <br>
        <br>
        <br>
        </font>
      </small>
    <%= image_tag("envelope.jpg") %>
  </h3>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<body>
  <div class="center jumbotron">
    <div id="panel">
      <p>
        <% list = %w[Basic_Class
                     Abbreviation
                     Communication
                     Exploring
                     Specialized_Class
                     Connection
                     Getting_Started] 
        %>
        <% list.sort.each do |val| %>
          <small><%= link_to "#{val.titleize}", url="##{val}" %></small>
          <br>
          <br>
        <% end %>
        </ul>
      </p>    
    </div>
    <div id="content">
      <% list = %w[basic_class 
                   specialized_class 
                   berserker 
                   warrior
                   swordsman
                   exploring
                   ninja
                   assassin
                   mage
                   cleric
                   brigand
                   wizard
                   witch
                   priest
                   monk
                   crusader
                   darkone
                   illusionlist
                   sorcerer
                   oracle
                   bard
                   ruffian
                   ranger
                   vampire
                   fundy
                   saint
                   necro
                   lich
                   connection
                   paladin
                   sage
                   conjurer
                   evangelist
                   getting_started
                   communication
                   abbreviation
                   thief] 
      %>
      <% list.sort.each do |val| %>
        <div id="help_list">
        <%= render "/static_pages/help_partials/#{val}" %>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/static_pages/history.html.erb
<% provide(:title, "History") %>
<h1>StaticPages#history</h1>
<p>Find me in app/views/static_pages/history.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Strange Home") %>

<body>
<div class="center jumbotron">
  
  <h1><font color="d1d1d1">Welcome to StrangeMUD<sup>&trade;</sup></font></h1>

  <h2>"Where thinking just might become a prerequisite"</h2>
  
  <h3>
    <%= image_tag("dice-medieval-alphap.png") %>
    <%= link_to "Play Now!", "http://www.phudbase.com/wm_client/", 
      :target => "_blank", 
      data: { confirm: "
      Enter the following info in the next page.
      Host: strangemud.net | Port: 9332"
      },
      class: "btn bt-lg btn-primary" %>
  </h3>
  
  <p>
    <small>
      StrangeMUD<sup>&trade;</sup> is a text-based multi-user real-time virtual 
      dungeons and dragons type game 
      (<a target="blank" href="https://en.wikipedia.org/wiki/MUD">MUD</a>). 
      The game has been running continuously since 1994. It is one of the 
      longest running MUDs out there! StrangeMUD<sup>&trade;</sup> had just 
      celebrated it's 20th anniversary!<br>
      <br>
      Running a heavily modified <a target="blank"
      href="http://www.circlemud.org/">CircleMUD 
      2.2</a> engine, it is anything but a MUD out of a box. A plethora of 
      insightful coders and creative builders have, over the years, 
      transformed it into a relaxed place online that many players call home.
      <br>
      <br>
      StrangeMUD<sup>&trade;</sup> offers 10 
      <a href="/help#Basic_class">basic class</a>: Warrior, Cleric, 
      Thief, Mage, Paladin, Brigand, Lich, Sage, Conjurer, & Evangelist. Each 
      primary class has a choice of two 
      <a href="/help#Specialized_Class">specialized class</a>. Both multiplay 
      and object sharing between characters are legal. Player killing(PK) is 
      optional above level 25 and clan membership is a popular way to make 
      a name for oneself. With over 80 open zones available, advancing in 
      the mortal ranks takes players through many unique areas as well as old 
      favorites.<br>
      <br>
      The most important asset to StrangeMUD<sup>&trade;</sup> is its players. 
      From any gods to helpful mortals, this MUD has something for everyone. 
      It is based on that which makes the world go around -- FUN.<br>
      <br>
      Thanks for visiting! Join us at telnet strangemud.net 9332
    </small>
  </p>
  
</div>

</body>

app/views/static_pages/testpage.html.erb
<h1>StaticPages#test</h1>

<script>
$(document).ready(function(){
    $("testing").click(function(){
        $("#div1").load("<%= about_path %>");
    });
});
</script>

<testing>Get External Content</testing>

<div id="div1" style="width:100%; height: 200px; margin:1%;">SHOW HERE!</div>

<br>
<br>

<div>
    
<iframe src="https://rails-tutorial-evilmuffin.c9users.io/" name="iframe_a"
  style="width:100%; height:100%; margin:1%;">
</iframe>
</div>


<!-- 

<script>
$(document).ready(function(){
    $("testing").click(function(){
        $("#div1").load("<%= user_path(path) %>");
    });
});
</script>

<div id="div1"></div>

<a href="<%= user_path(@users.find_by(id: 1)) %>">clicktest</a>

<%= link_to "clicky", user_path(@users.find_by(id: 1)) %>

<area id="myAnchor">
<area id="mapid" onchange="name=this.value;" />

<% hh = @users.find_by(id: 1) %>
<a href="<%= user_path(hh) %>">clicky</a>



<p>Click the button to return the value of its value attribute.</p>

<button value="value1" onclick="myFunction(this)">1</button>
<button value="value2" onclick="myFunction(this)">2</button>

<p id="output"></p>

<script>
function myFunction(button) {
    var x = button.value;
    document.getElementById("output").innerHTML = x;
}
</script>

-->

<!-- Just need to figure out how to pass the var x to rails at server side with ajax

<button value="Seita" onclick="myFunction(this)">1</button>
<button value="Abigale Kassulke" onclick="myFunction(this)">2</button>

<p id="output"></p>

<script>
function myFunction(button) {
    var x = button.value;
    $ajax({
        data : { data_value: JSON.stringify(x) }
    });
    $("#div1").load("<%= user_path.(@users.find_by(name: params[:data_value])) %>");
}
</script>

<div id="div1"></div>

-->