config/routes.rb
Rails.application.routes.draw do

  get 'areas/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'history' => 'static_pages#history'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'building' => 'static_pages#building'
  get 'news' => 'newsposts#news_page'
  get 'signup' => '#' #'users#new'
  get 'testpage' => 'static_pages#testpage'
  get 'delete_inactive_users' => 'users#delete_inactive_users'
  get 'messages' => 'messages#messages_board'
  get 'new_area' => 'areas#new'
  get 'worldmap' => 'areas#index'
  get 'showallareas' => 'areas#showall'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :newsposts, only: [:create, :edit, :update, :destroy]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :areas

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates(:user_id, presence: true)
  validates(:content, presence: true, length: { maximum: 150})
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user, only: [:create, :update, :edit, :destroy]
  before_action :correct_user, only: [:update, :edit, :destroy]
  
  def messages_board
    @message = current_user.messages.build if logged_in?
    @message_feed = Message.paginate(page: params[:page], per_page: 10)
  end
  
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = "Message posted"
      redirect_to messages_url
    else
      @message_feed = []
      render 'messages/messages_board'
    end
  end
  
  def edit
    @message = Message.find(params[:id])
  end
  
  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(message_params)
      flash[:success] = "Message updated"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    flash[:success] = "Post deleted"
    redirect_to current_user
  end
  
  private
  
    def message_params
      params.require(:message).permit(:content)
    end
    
    def correct_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_url if @message.nil?
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<% @user.messages.each do |message| %>
<li id="message-<%= message.id %>">
  <div class="user_pic">
    <% if message.user.picture? %>
      <%= image_tag message.user.picture.url %>
    <% else %>
      <%= image_tag("generic.jpg") %>
    <% end %>
  </div>
  <font color='d1d1d1'>
    <span class="user"><%= link_to message.user.name, message.user %></span>
    <span class="content"><%= message.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(message.created_at) %> ago.
    <% if current_user?(message.user) %>
      | <%= link_to "edit", edit_message_path(message) %>
      | <%= link_to "delete", message, method: :delete,
                                     data: { confirm: "Are you sure?" } %>
    <% end %>
  </span>
  </font>
</li>
<% end %>

app/views/messages/edit.html.erb
<% provide(:title, "Message Board") %>
<% provide(:button, "Save changes") %>
<div class="row">
  <aside class="col-md-4">
    <% if logged_in? %>
      <h3><font color="d1d1d1">Edit Message</font></h3>
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="message_form" %>
        <%= render 'shared/message_form' %>
      </section>
    <% else %>
      <font color='d1d1d1'>
         You must <%= link_to "log in", login_path %> in order to post a message.
      </font>
    <% end %>
  </aside>
</div>

app/views/messages/messages_board.html.erb
<% provide(:title, "Message Board") %>
<% provide(:button, "Post Message") %>
<div class="row">
  <aside class="col-md-4">
    <% if logged_in? %>
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="message_form" %>
        <%= render 'shared/message_form' %>
      </section>
    <% else %>
      <font color='d1d1d1'>
         You must <%= link_to "log in", login_path %> in order to post a message.
      </font>
    <% end %>
  </aside>
  <div class="col-md-8">
    <h3><font color="d1d1d1">Messages Posted</font></h3>
    <%= render 'shared/message_feed' %>
  </div>
</div>