config/routes.rb
Rails.application.routes.draw do

  get 'areas/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'history' => 'static_pages#history'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'building' => 'static_pages#building'
  get 'news' => 'newsposts#news_page'
  get 'signup' => '#' #'users#new'
  get 'testpage' => 'static_pages#testpage'
  get 'delete_inactive_users' => 'users#delete_inactive_users'
  get 'messages' => 'messages#messages_board'
  get 'new_area' => 'areas#new'
  get 'worldmap' => 'areas#index'
  get 'showallareas' => 'areas#showall'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :newsposts, only: [:create, :edit, :update, :destroy]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :areas

end

app/models/area.rb
class Area < ActiveRecord::Base
  default_scope -> { order(name: :asc) }
  validates(:name, presence: true, length: { maximum: 25 })
  validates(:coords, presence: true)
  validates(:box_location, presence: true)
  validates(:description, presence: true, length: { maximum: 200})
  validates(:creator, presence: true, length: { maximum: 50 })
  validates(:diff_from, presence: true)
  validate(:coords_pairs)
  validate(:coords_length)
  
  private
  
    #Validates if coords are in pairs
    def coords_pairs
      coords_length = coords.split(",").length
      if coords_length % 2 == 1
        errors.add(:coords, "should be in pairs")
      end
    end
    
    def coords_length
      coords_length = coords.split(",").length
      if coords_length < 6
        errors.add(:coords, "should be at less 3 pairs")
      end
    end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  
  def show
    @area = Area.find(params[:id])
  end
  
  def new
    @area = Area.new
  end
  
  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:success] = "Area successfully saved!"
      redirect_to worldmap_url
    else
      render 'new'
    end
  end
  
  def index
    @areas = Area.all
  end
  
  def showall
    @areas = Area.paginate(page: params[:page], per_page: 10)
  end
  
  def edit
    @area = Area.find(params[:id])
  end
  
  def update
    @area = Area.find(params[:id])
    if @area.update_attributes(area_params)
      flash[:success] = "Area updated"
      redirect_to worldmap_url
    else
      render 'edit'
    end
  end
  
  def destroy
    Area.find(params[:id]).destroy
    flash[:success] = "Area deleted"
    redirect_to worldmap_url
  end
  
  private
  
    def area_params
      params.require(:area).permit(:name, :coords, :box_location, :description,
                                   :creator, :diff_from, :diff_to)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="area_form">
    <% box = %w[left right top bottom] %>
    <% diff = ["Easy", "Medium","Slightly Difficult", "Difficult", "Deadly", 
               "Deadlier", "Impossible", "???"] %>
    <div id="area_form_left">
      <font color="d1d1d1"><%= f.label :name, "Area's Name" %></font>
      <%= f.text_field :name, 
          placeholder: "Must be less than 25 characters..." %>
          
      <font color="d1d1d1"><%= f.label :creator, "Creator" %></font>
      <%= f.text_field :creator, 
          placeholder: "Must be less than 50 characters..." %>
      
      <font color="d1d1d1">
        <%= f.label :box_location, "Info Box Location" %>
      </font>
      <%= f.select :box_location, box, class: 'form_control' %>
      
      <font color="d1d1d1"><%= f.label :diff_from, "Difficulty From" %></font>
      <%= f.select :diff_from, diff, class: 'form_control' %>
      
      <font color="d1d1d1"><%= f.label :diff_to, "To" %></font>
      <%= f.select :diff_to, diff, include_blank: true, class: 'form_control' %>
      <br><br>
      <%= f.submit yield(:button), class: "btn btn-primary" %>
    </div>
    <div id="area_form_right">
      <font color="d1d1d1"><%= f.label :coords, "Coordinates" %></font>
      <%= f.text_area :coords, 
       placeholder: "Must have at less 3 pairs.  Example: 11,11,22,22,33,33" %>
       
      <font color="d1d1d1"><%= f.label :description, "Area Description" %></font>
      <%= f.text_area :description, 
          placeholder: "Must be less than 200 characters..." %>
    </div>
  </div>
<% end %>
    
    

app/views/areas/edit.html.erb
<% provide(:title, 'Edit Area') %>
<% provide(:button, 'Save changes') %>
<h3>Edit Area</h3>

<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/areas/index.html.erb
<% provide(:title, "World Map") %>

<% if logged_in? %>
  <h3>
    World Map<br>
    <small>
      <%= link_to "List all areas", showallareas_path %>
      <%= link_to "(Add new area)", new_area_path if current_user.admin? %><br>
    </small>
  </h3>
<% else %>
  <h3>
    World Map<br>
    <small>
      <%= link_to "List all areas", showallareas_path %>
    </small>
  </h3>
<% end %>
<div class="map">
  <%= image_tag("strangemap.png", :usemap => "#worldmap", :class => "mapper") %>
  <map name="worldmap">
    <% @areas.each do |area| %>
      <% if logged_in? %>
        <% if current_user.admin? %>
          <% edit = area_path(area) %>
          <% title = "Click to edit or delete" %>
        <% else %>
          <% edit = "#" %>
          <% title = "" %>
        <% end %>
      <% else %>
        <% edit = "#" %>
        <% title = "" %>
      <% end %>
      <area class="target noborder"
            shape="poly" coords="<%= area.coords %>"
            data-box="<%= area.box_location %>"
            data-path="<%= area_path(area) %> #area_show"
            data-name="<%= area.name %>"
            data-bottom="<%= edit %>"
            href="<%= edit %>"
            title="<%= title %>">
            <!-- data-box, data-path and data-name are used in text_box.js -->
    <% end %>
    <% if logged_in? %>
        <% if current_user.admin? %>
          <% title = "Click to edit or delete" %>
        <% else %>
          <% title = "" %>
        <% end %>
      <% else %>
        <% title = "" %>
      <% end %>
    <span id="boxleft"></span>
    <span id="boxright"></span>
    <span id="boxtop"></span>
    <span id="boxbottom" title="<%= title %>"></span>
  </map>
</div>

<div class="map_help" id="div1">
  <br>
  <br>
  <font color="d1d1d1">
    Hover mouse over area for more information.
  </font>
</div>

<script src="mapper.js"></script>
<script src="text_box.js"></script>

app/views/areas/new.html.erb
<% provide(:button, 'Add New Area') %>
<% provide(:title, 'New Area') %>
<h3>New Area</h3>

<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/areas/show.html.erb
<% provide(:title, @area.name) %>

<div id="area_show">
  <font color="#d1d1d1">
    <%= @area.name %>
  </font>
  <br>
  <br>
  <ol class="area_show_details">
    <font color = "d1d1d1">
      <li><%= @area.description %></li>
      <br>
      <li>Difficulty - 
        <% if @area.diff_to? %>
          <%= @area.diff_from %> to <%= @area.diff_to %>
        <% else %>
          <%= @area.diff_from %>
        <% end %>
      </li>
      <li>Creator - <%= @area.creator %></li>
    </font>
  </ol>
</div>
<br>
<% if logged_in? %>
  <% divider = " | " %>
  <font color="d1d1d1">
    <%= link_to "Edit", edit_area_path(@area) if current_user.admin? %> 
    <%= divider if current_user.admin? %>
    <%= link_to "Delete", @area, method: :delete,
        data: { confirm: "Are you sure?" } if current_user.admin? %>
  </font>
<% end %>

app/views/areas/showall.html.erb
<% provide(:title, "Show All Areas") %>
<h3>List of Areas</h3>
<ol class="showall">
  <%= will_paginate %>
  <% @areas.each do |area| %>
    <li>
      <font color="#d1d1d1">
        <%= area.name %>
      </font>
      <blockquote class="blockquote">
        <small>
          <font color = "d1d1d1">
          <%= area.description %>
            <br>
            <br>  
          Difficulty - 
          <% if area.diff_to? %>
            <%= area.diff_from %> to <%= area.diff_to %>
          <% else %>
            <%= area.diff_from %>
          <% end %>
          <br>
          Creator - <%= area.creator %>
          </font>
        </small>
      </blockquote>
    </li>
  <% end %> 
  <%= will_paginate %>
</ol>