config/routes.rb
Rails.application.routes.draw do

  get 'areas/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'history' => 'static_pages#history'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  get 'building' => 'static_pages#building'
  get 'news' => 'newsposts#news_page'
  get 'signup' => '#' #'users#new'
  get 'testpage' => 'static_pages#testpage'
  get 'delete_inactive_users' => 'users#delete_inactive_users'
  get 'messages' => 'messages#messages_board'
  get 'new_area' => 'areas#new'
  get 'worldmap' => 'areas#index'
  get 'showallareas' => 'areas#showall'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :newsposts, only: [:create, :edit, :update, :destroy]
  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :areas

end

app/views/layouts/_footer.html.erb
<footer class="navbar-fixed-bottom">
  <small>
    The home of StrangeMUD<sup>&trade;</sup>
    <%= link_to image_tag("facebook.png", :class => "facebook_icon", 
        :alt => "Facebook"), 
        "https://www.facebook.com/groups/46967101209/?fref=nf", 
        :target => "_blank" %>
    <%= link_to image_tag("google.png", :class => "google_icon",
        :alt => "Google+"),
        'https://plus.google.com/+StrangemudNet', :target => "_blank" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "StrangeMUD&trade;".html_safe, root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "World", worldmap_path, 
                                 data: { no_turbolink: true } %></li>
        <li><%= link_to "News", news_path %></li>
        <li><%= link_to "Messages", messages_path %></li>
        <li><%= link_to "Building", building_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>